#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : alsa-tools
Version  : 1.2.5
Release  : 3
URL      : https://github.com/alsa-project/alsa-tools/archive/v1.2.5/alsa-tools-1.2.5.tar.gz
Source0  : https://github.com/alsa-project/alsa-tools/archive/v1.2.5/alsa-tools-1.2.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: alsa-tools-bin = %{version}-%{release}
Requires: alsa-tools-data = %{version}-%{release}
Requires: alsa-tools-lib = %{version}-%{release}
Requires: alsa-tools-license = %{version}-%{release}
Requires: alsa-tools-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : fltk-dev
BuildRequires : glibc-staticdev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
Patch1: 0001-Fix-build.patch

%description
VXLOADER - Firmware loader for Digigram VX soundcards
Takashi Iwai <tiwai@suse.de>

%package bin
Summary: bin components for the alsa-tools package.
Group: Binaries
Requires: alsa-tools-data = %{version}-%{release}
Requires: alsa-tools-license = %{version}-%{release}

%description bin
bin components for the alsa-tools package.


%package data
Summary: data components for the alsa-tools package.
Group: Data

%description data
data components for the alsa-tools package.


%package dev
Summary: dev components for the alsa-tools package.
Group: Development
Requires: alsa-tools-lib = %{version}-%{release}
Requires: alsa-tools-bin = %{version}-%{release}
Requires: alsa-tools-data = %{version}-%{release}
Provides: alsa-tools-devel = %{version}-%{release}
Requires: alsa-tools = %{version}-%{release}

%description dev
dev components for the alsa-tools package.


%package lib
Summary: lib components for the alsa-tools package.
Group: Libraries
Requires: alsa-tools-data = %{version}-%{release}
Requires: alsa-tools-license = %{version}-%{release}

%description lib
lib components for the alsa-tools package.


%package license
Summary: license components for the alsa-tools package.
Group: Default

%description license
license components for the alsa-tools package.


%package man
Summary: man components for the alsa-tools package.
Group: Default

%description man
man components for the alsa-tools package.


%prep
%setup -q -n alsa-tools-1.2.5
cd %{_builddir}/alsa-tools-1.2.5
%patch1 -p1

%build
## build_prepend content
for subdir in $(make list_subdirs); do
(cd $subdir && autoreconf -vfi);
done
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622494799
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make

%install
export SOURCE_DATE_EPOCH=1622494799
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/alsa-tools
cp %{_builddir}/alsa-tools-1.2.5/as10k1/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/9db6e6f4189b7101178eef598c9985910e51456d
cp %{_builddir}/alsa-tools-1.2.5/echomixer/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
cp %{_builddir}/alsa-tools-1.2.5/envy24control/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/133efad5329acf364135c569ac01ec084c3d4647
cp %{_builddir}/alsa-tools-1.2.5/hdspconf/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
cp %{_builddir}/alsa-tools-1.2.5/hdsploader/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
cp %{_builddir}/alsa-tools-1.2.5/hdspmixer/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
cp %{_builddir}/alsa-tools-1.2.5/ld10k1/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
cp %{_builddir}/alsa-tools-1.2.5/ld10k1/COPYING.LIB %{buildroot}/usr/share/package-licenses/alsa-tools/597bf5f9c0904bd6c48ac3a3527685818d11246d
cp %{_builddir}/alsa-tools-1.2.5/qlo10k1/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/133efad5329acf364135c569ac01ec084c3d4647
cp %{_builddir}/alsa-tools-1.2.5/rmedigicontrol/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/133efad5329acf364135c569ac01ec084c3d4647
cp %{_builddir}/alsa-tools-1.2.5/sb16_csp/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/133efad5329acf364135c569ac01ec084c3d4647
cp %{_builddir}/alsa-tools-1.2.5/seq/sbiload/COPYING %{buildroot}/usr/share/package-licenses/alsa-tools/133efad5329acf364135c569ac01ec084c3d4647
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/as10k1
/usr/bin/cspctl
/usr/bin/dl10k1
/usr/bin/echomixer
/usr/bin/envy24control
/usr/bin/hda-verb
/usr/bin/hdajackretask
/usr/bin/hdajacksensetest
/usr/bin/hdspconf
/usr/bin/hdsploader
/usr/bin/hdspmixer
/usr/bin/hwmixvolume
/usr/bin/init_audigy
/usr/bin/init_audigy_eq10
/usr/bin/init_live
/usr/bin/ld10k1
/usr/bin/ld10k1d
/usr/bin/lo10k1
/usr/bin/mixartloader
/usr/bin/pcxhrloader
/usr/bin/rmedigicontrol
/usr/bin/sbiload
/usr/bin/sscape_ctl
/usr/bin/us428control
/usr/bin/usx2yloader
/usr/bin/vxloader

%files data
%defattr(-,root,root,-)
/usr/share/applications/echomixer.desktop
/usr/share/applications/envy24control.desktop
/usr/share/applications/hdajackretask.desktop
/usr/share/applications/hdspconf.desktop
/usr/share/applications/hdspmixer.desktop
/usr/share/applications/hwmixvolume.desktop
/usr/share/icons/hicolor/128x128/apps/hdajackretask.png
/usr/share/icons/hicolor/128x128/apps/hwmixvolume.png
/usr/share/icons/hicolor/256x256/apps/hdajackretask.png
/usr/share/icons/hicolor/256x256/apps/hwmixvolume.png
/usr/share/icons/hicolor/48x48/apps/echomixer.png
/usr/share/icons/hicolor/48x48/apps/envy24control.png
/usr/share/icons/hicolor/48x48/apps/hdajackretask.png
/usr/share/icons/hicolor/48x48/apps/hdspconf.png
/usr/share/icons/hicolor/48x48/apps/hdspmixer.png
/usr/share/icons/hicolor/48x48/apps/hwmixvolume.png
/usr/share/ld10k1/effects/copy_2.emu10k1
/usr/share/ld10k1/effects/eq10.emu10k1
/usr/share/ld10k1/effects/fxbus.emu10k1
/usr/share/ld10k1/effects/mono_switch_2.emu10k1
/usr/share/ld10k1/effects/mono_switch_2x2.emu10k1
/usr/share/ld10k1/effects/output.emu10k1
/usr/share/ld10k1/effects/prologic.emu10k1
/usr/share/ld10k1/effects/simple.emu10k1
/usr/share/ld10k1/effects/sto51.emu10k1
/usr/share/ld10k1/effects/switch_2.emu10k1
/usr/share/ld10k1/effects/switch_2x2.emu10k1
/usr/share/ld10k1/effects/switch_6.emu10k1
/usr/share/ld10k1/effects/tone.emu10k1
/usr/share/ld10k1/effects/vol_2.emu10k1
/usr/share/ld10k1/effects/vol_master.emu10k1
/usr/share/sounds/opl3/drums.o3
/usr/share/sounds/opl3/drums.sb
/usr/share/sounds/opl3/std.o3
/usr/share/sounds/opl3/std.sb

%files dev
%defattr(-,root,root,-)
/usr/include/lo10k1/comm.h
/usr/include/lo10k1/ld10k1_error.h
/usr/include/lo10k1/ld10k1_fnc.h
/usr/include/lo10k1/liblo10k1.h
/usr/include/lo10k1/liblo10k1ef.h
/usr/include/lo10k1/liblo10k1lf.h
/usr/include/lo10k1/lo10k1.h
/usr/include/lo10k1/version.h
/usr/lib64/liblo10k1.so
/usr/share/aclocal/*.m4

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblo10k1.so.0
/usr/lib64/liblo10k1.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/alsa-tools/133efad5329acf364135c569ac01ec084c3d4647
/usr/share/package-licenses/alsa-tools/597bf5f9c0904bd6c48ac3a3527685818d11246d
/usr/share/package-licenses/alsa-tools/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
/usr/share/package-licenses/alsa-tools/9db6e6f4189b7101178eef598c9985910e51456d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cspctl.1
/usr/share/man/man1/envy24control.1
